name: codeland_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: 5.0.0
  dotted_border: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
